




# 线性方程

两个未知数的线性方程：

$$Ax + By + C = 0 $$

{A, B, C} 叫做参数，或者系数．{x, y} 未知数．我们把这样的方程称为二元一次方程，每一个二元一次方程都对应直角坐标系里的一条直线，每一条直角坐标系里的直线都对应一个二元一次方程．上面这句话可以翻译为：

* 如果有一个二元一次方程$Ax + By + C = 0$, {A, B, C}是确定的值，比如{1, 2, 3},
  那么所有$1 \cdot x + 2y + 3 = 0$的解(x, y)画到直角坐标系里面，会是一条直线．

* 如果在直角坐标系里面画一条直线，那么，在坐标系里直线上所有的点(x, y)都是一个二元一次线性方程的解．

我们可以先给一个二元一次方程，$y = 3x$, 那么这个二元一次方程的解有无限个，因为x随便取一个值，都可以求得一个y值．列举其中几个值{(1, 3), (1.5, 4.5), (2, 6), (3, 9)}，在直角坐标系中描点，我们可以看出，似乎这些点是在一条直线上．无论我们怎么去描点，二元一次方程有无数个组合，一个二元一次方程也有无数个解，那么怎么证明方程和直线一一对应？

首先，为什么一个二元一次方程对应一条直线？直线有什么性质？

一个二元一次方程的解对应一个点(x, y), 两点确定一条直线，任意找平面上的第三个点，这第三个点要在该直线上，那么，必须是在这两个点确定的那条直线上，否则这三个点不会在一条直线上．


```{theorem, lico, name="二元一次方程对应一条直线"}
若A, B, 不同时为零，
那么，
二元一次方程$Ax + By + C = 0$对应直角坐标系上一条直线

```

设$p_i(x_i, y_i), p_j(x_j, y_j)$是方程$Ax + By + C =0$的两个解．$d(p_i, p_j)$表示点$p_i, p_j$的距离．

$$d(p_i, p_j) = \sqrt{(x_{i} - x_{j})^2 + (y_{i} - y_{j})^2}$$


将$(x_i, y_i)$带入方程：

\begin{align}
Ax_i + By_i + C &= 0\\
Ax_j + By_j + C &= 0
\end{align}

若：$B = 0$ 且 $A =0$

那么$C = 0$, (x, y)将是整个坐标系平面上的点．

若：$B = 0$ 且　$A\neq 0$
$$Ax + C = 0$$
$$x = - \frac{C}{A}$$

x只能取一个值，y可以取任意值．

该二元一次方程是通过点(-C/A, 0)与x轴垂直的直线．

若$B\neq0$

$$y = -\frac{A}{B}x - \frac{C}{B}$$

\begin{align}
(y_{i} - y_{j})^2 &= \left((-\frac{A}{B}x_i - \frac{C}{B}) - (-\frac{A}{B}x_j - \frac{C}{B})\right)^2 \\
 					&= (\frac{A}{B})^2(x_i - x_j)^2
\end{align}

\begin{align}
d(p_i, p_j) &= \sqrt{(x_{i} - x_{j})^2 + (y_{i} - y_{j})^2} \\
            &= \sqrt{(x_{i} - x_{j})^2 + (\frac{A}{B})^2(x_i - x_j)^2} \\
            &= \sqrt{(1 + (\frac{A}{B})^2)(x_{i} - x_{j})^2} \\
			&= \sqrt{(1 + (\frac{A}{B})^2)}|x_i - x_j|
\end{align}

代入$p_1, p_2, p_3$

\begin{align}
d(p_1, p_2) &= \sqrt{(1 + (\frac{A}{B})^2)}|x_1 - x_2| \\
d(p_2, p_3) &= \sqrt{(1 + (\frac{A}{B})^2)}|x_2 - x_3| \\
d(p_1, p_3) &= \sqrt{(1 + (\frac{A}{B})^2)}|x_1 - x_3|
\end{align}

因为$p_1, p_2, p_3$是方程的三个不同解．因此，$x_1 \neq x_2 \neq x_3$

设$x_1 < x_2 < x_3$

\begin{align}
d(p_1, p_2) + d(p_2, p_3)&= \sqrt{(1 + (\frac{A}{B})^2)}|x_1 - x_3| \\
d(p_1, p_2) + d(p_2, p_3)&= d(p_1, p_3) = \sqrt{(1 + (\frac{A}{B})^2)}|x_1 - x_3|
\end{align}

若$p_1, p_2, p_3$不在一条直线上，那么$d(p_1, p_2) + d(p_2, p_3) > d(p_1, p_3)$(_三角形两边之和大于第三边_)与$d(p_1, p_2) + d(p_2, p_3) = d(p_1, p_3)$矛盾，因此，这三点必在一直线上．

直观的考虑，两点之间直线距离最短，$d(p_1, p_2) + d(p_2, p_3) = d(p_1, p_3)$,
那么$p_2$点必须在$p_1, p_3$连线的直线之间．

这就意味着，如果我们求得二元一次方程的任意两个解，$p_1(x_1, x_2), p_2(x_2,
y_2)$，我们在坐标系上画通过这两个点的直线，那么其他的解都将在$p_1p_2$这条直线上．


```{theorem, coli, name="坐标系的每一条直线对应一个直线方程"}
若坐标系里有一条直线，那么这条直线对应一个二元一次方程．

```

设坐标系里有一条直线，上面有两个点$p_1(x_1, y_1), p_2(x_2, y_2)$．

若有一个二元一次方程$$Ax + By + C = 0$$满足这两个点，那么：

若$x_1 = x_2$

\begin{align}
Ax_1 + By_1 + C &= 0\\
Ax_2 + By_2 + C &= 0 
\end{align}

$$B(y_2 - y_1) = 0$$
因为是两个不同的点，$y_2 \neq y_1$，那么B = 0
$$x = - \frac{C}{A}$$
因此：
$$-\frac{C}{A} = x_1 = x_2$$,

代入：$Ax + By + C = 0$, 有二元一次方程：
$$x = x_1$$

若$x_1 \neq x_2$

\begin{align}
Ax_1 + By_1 + C &= 0\\
Ax_2 + By_2 + C &= 0 
\end{align}

消系数A：

\begin{align}
Ax_1x_2 + Bx_2y_1 + Cx_2 &= 0\\
Ax_1x_2 + Bx_1y_2 + Cx_1 &= 0 \\
B(x_1y_2 - x_2y_1) &= - C(x_1 - x_2)
\end{align}

若$x_1y_2 - x_2y_1 = 0$, 那么，$C = 0$
$$Ax + By = 0$$
$$y = - \frac{A}{B}x$$
$x_1, x_2$不相等，设$x_1$不等于零．
\begin{align}
Ax_1 + By_1 = 0 \\
\frac{y_1}{x_1} &= - \frac{A}{B} 
\end{align}

那么有二元一次方程$y = \frac{y_1}{x_1}x$

若$x_1y_2 - x_2y_1 \neq 0$

$$ B = - \frac{C(x_1 - x_2)}{x_1y_2 - x_2y_1} $$
$$ A = - \frac{C(y_2 - y_1)}{x_1y_2 - x_2y_1} $$

代入$Ax + By + C = 0$

$$- \frac{C(y_2 - y_1)}{x_1y_2 - x_2y_1}x + (- \frac{C(x_1 - x_2)}{x_1y_2 - x_2y_1})y + C = 0$$

$$-y_2x+ y_1x - x_1y + x_2y + x_1y_2 - x_2y_1 = 0$$

把$(x_1, y_1), (x_2, y_2)$代入该方程，等式成立．

因此，直线上的两个点能找到一个二元一次方程，根据定理\@ref(thm:lico)，该方程对应坐标系上一条直线，那么二元一次方程对应的直线，必然是该直线．这就找到直线的二元一次方程．


